#
# Generated by generate_plugin.py.
#
# init.tmux: called by plugin.sh.tmux to initialize the plugin.
#

display -p '[tmux-which-key] Loading plugin ...'

#
# User options
#

set -g @wk_cfg_key_prefix_table "Space"
set -g @wk_cfg_title_style "align=centre,bold"
set -g @wk_cfg_title_prefix "tmux"
set -g @wk_cfg_title_prefix_style "fg=green,align=centre,bold"
set -g @wk_cfg_pos_x "R"
set -g @wk_cfg_pos_y "P"

#
# Custom variables
#

setenv -h log_info "#[fg=green,italics] [info]#[default]#[italics]"

#
# Menus
#

set -g @wk_menu_copy \
'Copy "c" copy-mode \
"List buffers" "#" list-buffers'

set -g @wk_menu_layout \
'Next "l" "nextl ; show-wk-menu #{@wk_menu_layout}" \
Tiled "t" "selectnl tiled" \
Horizontal "h" "selectl even-horizontal" \
Vertical "v" "selectl even-vertical" \
"Horizontal main" "H" "selectl main-horizontal" \
"Vertical main" "V" "selectl main-vertical"'

set -g @wk_menu_worktrees \
'Choose "w" "run-shell -b \"~/.config/tmux/plugins/tmux-worktrees/scripts/worktree-manager.sh choose\"" \
Cleanup "d" "run-shell -b \"~/.config/tmux/plugins/tmux-worktrees/scripts/worktree-manager.sh cleanup\""'

set -g @wk_menu_windows \
'Last "tab" last-window \
Choose "w" "choose-tree -Zw" \
Previous "p" previous-window \
Next "n" next-window \
New "c" "neww -c #{pane_current_path}" \
"" \
"+Layout" "l" "show-wk-menu #{@wk_menu_layout}" \
"Split horizontal" "/" "splitw -h -c #{pane_current_path}" \
"Split vertical" "-" "splitw -v -c #{pane_current_path}" \
Rotate "o" "rotatew ; show-wk-menu #{@wk_menu_windows}" \
"Rotate reverse" "O" "rotatew -D ; show-wk-menu #{@wk_menu_windows}" \
"" \
Rename "R" "command-prompt -I \"#W\" \"renamew -- \\"%%\\"\"" \
Kill "X" "confirm -p \"Kill window #W? (y/n)\" killw" \
"" \
"+Worktrees" "W" "show-wk-menu #{@wk_menu_worktrees}"'

set -g @wk_menu_resize \
'Left "h" "resizep -L ; show-wk-menu #{@wk_menu_resize}" \
Down "j" "resizep -D ; show-wk-menu #{@wk_menu_resize}" \
Up "k" "resizep -U ; show-wk-menu #{@wk_menu_resize}" \
Right "l" "resizep -R ; show-wk-menu #{@wk_menu_resize}" \
"Left more" "H" "resizep -L 10 ; show-wk-menu #{@wk_menu_resize}" \
"Down more" "J" "resizep -D 10 ; show-wk-menu #{@wk_menu_resize}" \
"Up more" "K" "resizep -U 10 ; show-wk-menu #{@wk_menu_resize}" \
"Right more" "L" "resizep -R 10 ; show-wk-menu #{@wk_menu_resize}"'

set -g @wk_menu_panes \
'Last "tab" lastp \
Choose "p" "displayp -d 0" \
"" \
Left "h" "selectp -L" \
Down "j" "selectp -D" \
Up "k" "selectp -U" \
Right "l" "selectp -R" \
"" \
Zoom "z" "resizep -Z" \
"+Resize" "r" "show-wk-menu #{@wk_menu_resize}" \
"Swap left" "H" "swapp -t \"{left-of}\"" \
"Swap down" "J" "swapp -t \"{down-of}\"" \
"Swap up" "K" "swapp -t \"{up-of}\"" \
"Swap right" "L" "swapp -t \"{right-of}\"" \
Break "!" break-pane \
"" \
Mark "m" "selectp -m" \
Unmark "M" "selectp -M" \
Capture "C" capture-pane \
"Respawn pane" "R" restart-pane \
Kill "X" "confirm -p \"Kill pane #P? (y/n)\" killp"'

set -g @wk_menu_buffers \
'Choose "b" "choose-buffer -Z" \
List "l" lsb \
Paste "p" pasteb'

set -g @wk_menu_resurrect \
'"Save session" "s" "run-shell ~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh" \
"Restore session" "r" "run-shell ~/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh"'

set -g @wk_menu_snapshots \
'"Save named" "s" "command-prompt -p \"Snapshot name:\" \"run-shell ~/.config/tmux/plugins/tmux-named-snapshot/scripts/save-snapshot.sh %%\"" \
"Restore named" "r" "command-prompt -p \"Snapshot name:\" \"run-shell ~/.config/tmux/plugins/tmux-named-snapshot/scripts/restore-snapshot.sh %%\"" \
"Pick snapshot" "p" "display-popup -E -d \"#{pane_current_path}\" -h 40% -w 50% ~/.config/tmux/scripts/snapshot-picker.sh"'

set -g @wk_menu_sessions \
'Choose "s" "choose-tree -Zs" \
New "N" new \
Rename "r" rename \
"" \
"New AOE session" "a" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 80% -e TMUX_PARENT_CLIENT=#{client_tty} ~/.config/tmux/scripts/aoen-session.sh" \
"New AOE session (any folder, pick profile)" "A" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 80% -e TMUX_PARENT_CLIENT=#{client_tty} ~/.config/tmux/scripts/aoe-profile-session.sh" \
"Session picker" "p" "display-popup -E -d \"#{pane_current_path}\" -w 50% -h 40% ~/.config/tmux/scripts/session-picker.sh" \
"Sessionizer (projects)" "f" "display-popup -E -d \"#{pane_current_path}\" -w 60% -h 50% ~/.config/tmux/scripts/sessionizer.sh" \
"Session wizard" "w" "display-popup -E -h 40% -w 80% ~/.config/tmux/plugins/tmux-session-wizard/bin/t" \
"SSH to host (ft)" "t" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 80% ~/.local/bin/ft.sh" \
"" \
"+Resurrect" "R" "show-wk-menu #{@wk_menu_resurrect}" \
"+Snapshots" "S" "show-wk-menu #{@wk_menu_snapshots}"'

set -g @wk_menu_plugins \
'Install "i" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/install_plugins" \
Update "u" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/update_plugins" \
Clean "c" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/clean_plugins"'

set -g @wk_menu_client \
'Choose "c" "choose-client -Z" \
Last "l" "switchc -l" \
Previous "p" "switchc -p" \
Next "n" "switchc -n" \
"" \
Refresh "R" refresh \
"+Plugins" "P" "show-wk-menu #{@wk_menu_plugins}" \
Detach "D" detach \
Suspend "Z" suspendc \
"" \
"Reload config" "r" reload-config \
Customize "," "customize-mode -Z"'

set -g @wk_menu_harpoon \
'List "l" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -l\"" \
"Add window" "a" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -a\"" \
"" \
"Slot 1" "1" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -s 1\"" \
"Slot 2" "2" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -s 2\"" \
"Slot 3" "3" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -s 3\"" \
"" \
"Pin to slot 1" "H" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -r 1\""'

set -g @wk_menu_gitlab \
'"Open repo" "O" "run-shell \"~/.config/tmux/scripts/glab-open.sh repo #{pane_current_path}\"" \
"Latest pipeline" "P" "run-shell \"~/.config/tmux/scripts/glab-open.sh pipeline #{pane_current_path}\"" \
"Pipelines list" "I" "run-shell \"~/.config/tmux/scripts/glab-open.sh pipelines-list #{pane_current_path}\"" \
"Pipeline TUI" "C" "display-popup -E -d \"#{pane_current_path}\" -h 85% -w 85% \"fish -c \\"glab ci view\\"\"" \
"" \
"CI status" "S" "display-popup -E -d \"#{pane_current_path}\" -h 50% -w 80% \"glab ci status 2>&1; echo; read _\"" \
"MR list" "L" "display-popup -E -d \"#{pane_current_path}\" -h 50% -w 80% \"glab mr list 2>&1; echo; read _\"" \
"Review MR (tuicr)" "R" "display-popup -E -d \"#{pane_current_path}\" -h 90% -w 95% \"~/.config/tmux/scripts/glab-mr-review.sh || read _\"" \
"Create MR" "M" "display-popup -E -d \"#{pane_current_path}\" -h 80% -w 80% \"glab mr create\"" \
"View MR" "V" "run-shell \"glab mr view --web\"" \
"" \
"Local CI setup" "u" "display-popup -E -d \"#{pane_current_path}\" -w 90% -h 75% \"bash ~/.config/tmux/scripts/gcl-setup.sh #{pane_current_path}\"" \
"Pipeline TUI (Local)" "v" "new-window -c \"#{pane_current_path}\" -n gctui \"~/.local/bin/gctui #{pane_current_path}\"" \
"Pipeline TUI (Remote)" "d" "new-window -c \"#{pane_current_path}\" -n gctui:remote \"~/.local/bin/gctui --remote #{pane_current_path}\"" \
"Config view" "y" "new-window -c \"#{pane_current_path}\" -n gctui:cfg \"~/.local/bin/gctui --config #{pane_current_path}\"" \
"Dual view (local + remote)" "w" "run-shell \"tmuxinator start ci root=#{pane_current_path}\"" \
"Assemble pipeline" "j" "display-popup -E -d \"#{pane_current_path}\" -w 90% -h 70% \"~/.local/bin/gctui assemble #{pane_current_path}; read _\""'

set -g @wk_menu_parallel \
'"AOE scratchpad" "O" "display-popup -E -w 85% -h 85% -e TMUX_PARENT_CLIENT=#{client_tty} ~/.config/tmux/scripts/aoe-scratchpad.sh" \
"All Claude sessions (every repo)" "l" "display-popup -E -d \"#{pane_current_path}\" -w 90% -h 80% -e TMUX_PARENT_CLIENT=#{client_tty} ~/.config/tmux/scripts/aoe-claude-sessions.sh" \
"" \
"Spawn ticket swarm" "s" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 60% \"~/.config/tmux/scripts/swarm.sh interactive\"" \
"Swarm control session" "S" "run-shell \"tmuxinator start swarm root=#{pane_current_path}\"" \
"Swarm dashboard" "d" "display-popup -E -d \"#{pane_current_path}\" -w 90% -h 60% \"~/.config/tmux/scripts/swarm-dashboard.sh watch\"" \
"" \
"Review layout" "r" "run-shell \"tmuxinator start review root=#{pane_current_path} id=rev\"" \
"Pipeline layout" "p" "run-shell \"tmuxinator start pipeline root=#{pane_current_path} id=p\"" \
"Monitor layout" "m" "run-shell \"tmuxinator start monitor root=#{pane_current_path}\"" \
"Workflow (orchestrator)" "o" "run-shell \"tmuxinator start workflow root=#{pane_current_path} id=wf\"" \
"" \
"Autopilot status" "a" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 50% \"~/.config/tmux/scripts/autopilot.sh list; echo; read _\"" \
"Peek a worker" "P" "display-popup -E -d \"#{pane_current_path}\" -w 90% -h 70% \"~/.config/tmux/scripts/swarm.sh peek-i\"" \
"Reap done workers" "R" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 50% \"~/.config/tmux/scripts/swarm.sh reap-done; echo; read _\"" \
"Teardown swarm" "x" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 50% \"~/.config/tmux/scripts/swarm.sh teardown; echo; read _\""'

set -g @wk_menu_sessionsfzfvi \
'"By name" "n" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh sessions name" \
"By content (FTS)" "c" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh sessions content" \
"By project" "p" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh pick project" \
"By agent" "a" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh pick agent" \
"By health grade" "g" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh pick grade" \
"By outcome" "O" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh pick outcome" \
"With tool failures" "F" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh sessions failures" \
All "r" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh sessions all"'

set -g @wk_menu_secretsfzfvi \
'"All findings" "l" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh secrets all" \
"By project" "p" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh secrets pick project" \
"By agent" "a" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh secrets pick agent" \
"Scan now" "x" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh secrets scan"'

set -g @wk_menu_context \
'"Context total (transcript, no /context)" "c" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_full_context.sh\"" \
"Live /context (sends to REPL)" "L" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_live_context.sh\"" \
"System prompt" "y" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_system_prompt.sh\"" \
"System tools" "t" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_system_tools.sh\"" \
"MCP servers" "m" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_mcp.sh\"" \
"Custom agents" "a" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_agents.sh\"" \
"Memory / CLAUDE.md" "f" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_memory_files.sh\"" \
"Files loaded into context" "i" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_context_files.sh\"" \
Messages "g" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_messages.sh\"" \
"Session health / intel (current)" "h" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_health.sh\"" \
Permissions "p" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_permissions.sh\"" \
Skills "k" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_skills.sh\"" \
"Cost / usage (session)" "o" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_cost.sh\"" \
"Daily usage / cost" "u" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_usage.sh\"" \
"" \
"+Sessions (fzf vi)" "s" "show-wk-menu #{@wk_menu_sessionsfzfvi}" \
"+Secrets (fzf vi)" "S" "show-wk-menu #{@wk_menu_secretsfzfvi}" \
"Health / intel overview (all)" "H" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_health_overview.sh\"" \
"Stats (28d, less)" "x" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh stats" \
"Projects browser" "r" "display-popup -E -d \"#{pane_current_path}\" -w 92% -h 88% -e TMUX_PARENT_CLIENT=#{client_tty} /home/froa/tmux-context-inspector/scripts/av_browse.sh projects" \
"" \
"Web UI — session insights (current)" "w" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/open_web.sh session\"" \
"Web UI — insights dashboard (all)" "W" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/open_web.sh insights\"" \
Help "?" "run-shell -b \"/home/froa/tmux-context-inspector/scripts/show_help.sh\""'

set -g @wk_menu_jot \
'Open "j" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh main #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
Switch "s" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh switch #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
"Search content" "w" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh content_search #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
Cleanup "k" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh cleanup #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
Doctor "d" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh doctor #{q:client_name} #{q:session_name} > /dev/null 2>&1\""'

set -g @wk_menu_logging \
'"Toggle logging" "t" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/toggle_logging.sh" \
"Save history" "s" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/save_complete_history.sh" \
"Screen capture" "c" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/screen_capture.sh" \
"Clear history" "x" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/clear_history.sh"'

set -g @wk_menu_tools \
'FZF "f" "run-shell -b ~/.config/tmux/plugins/tmux-fzf/main.sh" \
Extrakto "e" "run-shell \"\\"~/.config/tmux/plugins/extrakto/scripts/open.sh\\" \\"#{pane_id}\\"\"" \
1Password "u" "split-window -l 10 ~/.config/tmux/plugins/tmux-1password/scripts/main.sh #{pane_id}" \
"Scratch terminal" "g" "display-popup -E -d \"#{pane_current_path}\" -w 80% -h 80%" \
"" \
"+Jot" "j" "show-wk-menu #{@wk_menu_jot}" \
"+Logging" "l" "show-wk-menu #{@wk_menu_logging}" \
"" \
"Yank line" "y" "run-shell -b ~/.config/tmux/plugins/tmux-yank/scripts/copy_line.sh" \
"Yank PWD" "Y" "run-shell -b ~/.config/tmux/plugins/tmux-yank/scripts/copy_pane_pwd.sh"'

set -g @wk_menu_overseer \
'"User access (subscriptions + roles)" "p" "command-prompt -p \"User (UPN/email/objectId):\" \"display-popup -E -d \\"#{pane_current_path}\\" -w 90% -h 75% \\"~/.config/tmux/scripts/show-user-access.sh '%%' 2>&1; echo; read _\\"\""'

set -g @wk_menu_root \
'Run "space" command-prompt \
"Last window" "tab" last-window \
"Last pane" "`" last-pane \
Copy "c" "show-wk-menu #{@wk_menu_copy}" \
"" \
"+Windows" "w" "show-wk-menu #{@wk_menu_windows}" \
"+Panes" "p" "show-wk-menu #{@wk_menu_panes}" \
"+Buffers" "b" "show-wk-menu #{@wk_menu_buffers}" \
"+Sessions" "s" "show-wk-menu #{@wk_menu_sessions}" \
"+Client" "C" "show-wk-menu #{@wk_menu_client}" \
"" \
"+Harpoon" "h" "show-wk-menu #{@wk_menu_harpoon}" \
"+GitLab" "g" "show-wk-menu #{@wk_menu_gitlab}" \
"+Parallel" "A" "show-wk-menu #{@wk_menu_parallel}" \
"+Context" "K" "show-wk-menu #{@wk_menu_context}" \
"+Tools" "t" "show-wk-menu #{@wk_menu_tools}" \
"" \
"+Overseer" "o" "show-wk-menu #{@wk_menu_overseer}" \
"" \
tmux-menus "M" "run-shell ~/.config/tmux/plugins/tmux-menus/items/main.sh" \
Time "T" clock-mode \
"Show messages" "\~" show-messages \
"+Keys" "?" "list-keys -N"'

#
# Macros
#

set -gF @wk_cmd_show \
"display-menu \
-x '#{@wk_cfg_pos_x}' \
-y '#{@wk_cfg_pos_y}' \
-T '#[#{@wk_cfg_title_style}]#[#{@wk_cfg_title_prefix_style}]#{@wk_cfg_title_prefix}#[#{@wk_cfg_title_style}]'"

set -gF command-alias[200] show-wk-menu=\
'#{@wk_cmd_show}'

set -gF command-alias[201] show-wk-menu-root=\
'#{@wk_cmd_show} #{@wk_menu_root}'

set -gF command-alias[202] reload-config=\
'display "#{log_info} Loading config... " ; \
source-file $HOME/.tmux.conf ; \
display -p "\n\n... Press ENTER to continue"'

set -gF command-alias[203] restart-pane=\
'display "#{log_info} Restarting pane" ; \
respawnp -k -c #{pane_current_path}'

#
# Keybindings
#

display -p "[tmux-which-key] Binding prefix table key to #{@wk_cfg_key_prefix_table} ..."
run-shell "tmux bind-key -Tprefix #{@wk_cfg_key_prefix_table} show-wk-menu-root"

display -p '[tmux-which-key] Done'
