#
# Generated by generate_plugin.py.
#
# init.tmux: called by plugin.sh.tmux to initialize the plugin.
#

display -p '[tmux-which-key] Loading plugin ...'

#
# User options
#

set -g @wk_cfg_key_prefix_table "Space"
set -g @wk_cfg_title_style "align=centre,bold"
set -g @wk_cfg_title_prefix "tmux"
set -g @wk_cfg_title_prefix_style "fg=green,align=centre,bold"
set -g @wk_cfg_pos_x "R"
set -g @wk_cfg_pos_y "P"

#
# Custom variables
#

setenv -h log_info "#[fg=green,italics] [info]#[default]#[italics]"

#
# Menus
#

set -g @wk_menu_copy \
'Copy "c" copy-mode \
"List buffers" "#" list-buffers'

set -g @wk_menu_layout \
'Next "l" "nextl ; show-wk-menu #{@wk_menu_layout}" \
Tiled "t" "selectnl tiled" \
Horizontal "h" "selectl even-horizontal" \
Vertical "v" "selectl even-vertical" \
"Horizontal main" "H" "selectl main-horizontal" \
"Vertical main" "V" "selectl main-vertical"'

set -g @wk_menu_worktrees \
'Choose "w" "run-shell -b \"~/.config/tmux/plugins/tmux-worktrees/scripts/worktree-manager.sh choose\"" \
Cleanup "d" "run-shell -b \"~/.config/tmux/plugins/tmux-worktrees/scripts/worktree-manager.sh cleanup\""'

set -g @wk_menu_windows \
'Last "tab" last-window \
Choose "w" "choose-tree -Zw" \
Previous "p" previous-window \
Next "n" next-window \
New "c" "neww -c #{pane_current_path}" \
"" \
"+Layout" "l" "show-wk-menu #{@wk_menu_layout}" \
"Split horizontal" "/" "splitw -h -c #{pane_current_path}" \
"Split vertical" "-" "splitw -v -c #{pane_current_path}" \
Rotate "o" "rotatew ; show-wk-menu #{@wk_menu_windows}" \
"Rotate reverse" "O" "rotatew -D ; show-wk-menu #{@wk_menu_windows}" \
"" \
Rename "R" "command-prompt -I \"#W\" \"renamew -- \\"%%\\"\"" \
Kill "X" "confirm -p \"Kill window #W? (y/n)\" killw" \
"" \
"+Worktrees" "W" "show-wk-menu #{@wk_menu_worktrees}"'

set -g @wk_menu_resize \
'Left "h" "resizep -L ; show-wk-menu #{@wk_menu_resize}" \
Down "j" "resizep -D ; show-wk-menu #{@wk_menu_resize}" \
Up "k" "resizep -U ; show-wk-menu #{@wk_menu_resize}" \
Right "l" "resizep -R ; show-wk-menu #{@wk_menu_resize}" \
"Left more" "H" "resizep -L 10 ; show-wk-menu #{@wk_menu_resize}" \
"Down more" "J" "resizep -D 10 ; show-wk-menu #{@wk_menu_resize}" \
"Up more" "K" "resizep -U 10 ; show-wk-menu #{@wk_menu_resize}" \
"Right more" "L" "resizep -R 10 ; show-wk-menu #{@wk_menu_resize}"'

set -g @wk_menu_panes \
'Last "tab" lastp \
Choose "p" "displayp -d 0" \
"" \
Left "h" "selectp -L" \
Down "j" "selectp -D" \
Up "k" "selectp -U" \
Right "l" "selectp -R" \
"" \
Zoom "z" "resizep -Z" \
"+Resize" "r" "show-wk-menu #{@wk_menu_resize}" \
"Swap left" "H" "swapp -t \"{left-of}\"" \
"Swap down" "J" "swapp -t \"{down-of}\"" \
"Swap up" "K" "swapp -t \"{up-of}\"" \
"Swap right" "L" "swapp -t \"{right-of}\"" \
Break "!" break-pane \
"" \
Mark "m" "selectp -m" \
Unmark "M" "selectp -M" \
Capture "C" capture-pane \
"Respawn pane" "R" restart-pane \
Kill "X" "confirm -p \"Kill pane #P? (y/n)\" killp"'

set -g @wk_menu_buffers \
'Choose "b" "choose-buffer -Z" \
List "l" lsb \
Paste "p" pasteb'

set -g @wk_menu_resurrect \
'"Save session" "s" "run-shell ~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh" \
"Restore session" "r" "run-shell ~/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh"'

set -g @wk_menu_snapshots \
'"Save named" "s" "command-prompt -p \"Snapshot name:\" \"run-shell ~/.config/tmux/plugins/tmux-named-snapshot/scripts/save-snapshot.sh %%\"" \
"Restore named" "r" "command-prompt -p \"Snapshot name:\" \"run-shell ~/.config/tmux/plugins/tmux-named-snapshot/scripts/restore-snapshot.sh %%\"" \
"Pick snapshot" "p" "display-popup -E -d \"#{pane_current_path}\" -h 40% -w 50% ~/.config/tmux/scripts/snapshot-picker.sh"'

set -g @wk_menu_sessions \
'Choose "s" "choose-tree -Zs" \
New "N" new \
Rename "r" rename \
"" \
"+Resurrect" "R" "show-wk-menu #{@wk_menu_resurrect}" \
"+Snapshots" "S" "show-wk-menu #{@wk_menu_snapshots}"'

set -g @wk_menu_plugins \
'Install "i" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/install_plugins" \
Update "u" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/update_plugins" \
Clean "c" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/clean_plugins"'

set -g @wk_menu_client \
'Choose "c" "choose-client -Z" \
Last "l" "switchc -l" \
Previous "p" "switchc -p" \
Next "n" "switchc -n" \
"" \
Refresh "R" refresh \
"+Plugins" "P" "show-wk-menu #{@wk_menu_plugins}" \
Detach "D" detach \
Suspend "Z" suspendc \
"" \
"Reload config" "r" reload-config \
Customize "," "customize-mode -Z"'

set -g @wk_menu_harpoon \
'List "l" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -l\"" \
"Add window" "a" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -a\"" \
"" \
"Slot 1" "1" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -s 1\"" \
"Slot 2" "2" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -s 2\"" \
"Slot 3" "3" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -s 3\"" \
"" \
"Pin to slot 1" "H" "run-shell \"~/.config/tmux/plugins/tmux-harpoon/harpoon -r 1\""'

set -g @wk_menu_gitlab \
'"Open repo" "r" "run-shell \"~/.config/tmux/scripts/glab-open.sh repo #{pane_current_path}\"" \
"Latest pipeline" "p" "run-shell \"~/.config/tmux/scripts/glab-open.sh pipeline #{pane_current_path}\"" \
"Pipelines list" "l" "run-shell \"~/.config/tmux/scripts/glab-open.sh pipelines-list #{pane_current_path}\"" \
"Pipeline TUI" "c" "display-popup -E -d \"#{pane_current_path}\" -h 85% -w 85% \"fish -c \\"glab ci view\\"\"" \
"" \
"CI status" "s" "display-popup -E -d \"#{pane_current_path}\" -h 50% -w 80% \"glab ci status 2>&1; echo; read _\"" \
"MR list" "m" "display-popup -E -d \"#{pane_current_path}\" -h 50% -w 80% \"glab mr list 2>&1; echo; read _\"" \
"Create MR" "R" "display-popup -E -d \"#{pane_current_path}\" -h 80% -w 80% \"glab mr create\"" \
"View MR" "v" "run-shell \"glab mr view --web\""'

set -g @wk_menu_jot \
'Open "j" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh main #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
Switch "s" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh switch #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
"Search content" "w" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh content_search #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
Cleanup "k" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh cleanup #{q:client_name} #{q:session_name} > /dev/null 2>&1\"" \
Doctor "d" "run-shell \"~/.config/tmux/plugins/tmux-jot/scripts/jot.sh doctor #{q:client_name} #{q:session_name} > /dev/null 2>&1\""'

set -g @wk_menu_logging \
'"Toggle logging" "t" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/toggle_logging.sh" \
"Save history" "s" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/save_complete_history.sh" \
"Screen capture" "c" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/screen_capture.sh" \
"Clear history" "x" "run-shell ~/.config/tmux/plugins/tmux-logging/scripts/clear_history.sh"'

set -g @wk_menu_tools \
'FZF "f" "run-shell -b ~/.config/tmux/plugins/tmux-fzf/main.sh" \
Extrakto "e" "run-shell \"\\"~/.config/tmux/plugins/extrakto/scripts/open.sh\\" \\"#{pane_id}\\"\"" \
"" \
"+Jot" "j" "show-wk-menu #{@wk_menu_jot}" \
"+Logging" "l" "show-wk-menu #{@wk_menu_logging}" \
"" \
"Yank line" "y" "run-shell -b ~/.config/tmux/plugins/tmux-yank/scripts/copy_line.sh" \
"Yank PWD" "Y" "run-shell -b ~/.config/tmux/plugins/tmux-yank/scripts/copy_pane_pwd.sh"'

set -g @wk_menu_root \
'Run "space" command-prompt \
"Last window" "tab" last-window \
"Last pane" "`" last-pane \
Copy "c" "show-wk-menu #{@wk_menu_copy}" \
"" \
"+Windows" "w" "show-wk-menu #{@wk_menu_windows}" \
"+Panes" "p" "show-wk-menu #{@wk_menu_panes}" \
"+Buffers" "b" "show-wk-menu #{@wk_menu_buffers}" \
"+Sessions" "s" "show-wk-menu #{@wk_menu_sessions}" \
"+Client" "C" "show-wk-menu #{@wk_menu_client}" \
"" \
"+Harpoon" "h" "show-wk-menu #{@wk_menu_harpoon}" \
"+GitLab" "g" "show-wk-menu #{@wk_menu_gitlab}" \
"+Tools" "t" "show-wk-menu #{@wk_menu_tools}" \
"" \
Time "T" clock-mode \
"Show messages" "\~" show-messages \
"+Keys" "?" "list-keys -N"'

#
# Macros
#

set -gF @wk_cmd_show \
"display-menu \
-x '#{@wk_cfg_pos_x}' \
-y '#{@wk_cfg_pos_y}' \
-T '#[#{@wk_cfg_title_style}]#[#{@wk_cfg_title_prefix_style}]#{@wk_cfg_title_prefix}#[#{@wk_cfg_title_style}]'"

set -gF command-alias[200] show-wk-menu=\
'#{@wk_cmd_show}'

set -gF command-alias[201] show-wk-menu-root=\
'#{@wk_cmd_show} #{@wk_menu_root}'

set -gF command-alias[202] reload-config=\
'display "#{log_info} Loading config... " ; \
source-file $HOME/.tmux.conf ; \
display -p "\n\n... Press ENTER to continue"'

set -gF command-alias[203] restart-pane=\
'display "#{log_info} Restarting pane" ; \
respawnp -k -c #{pane_current_path}'

#
# Keybindings
#

display -p "[tmux-which-key] Binding prefix table key to #{@wk_cfg_key_prefix_table} ..."
run-shell "tmux bind-key -Tprefix #{@wk_cfg_key_prefix_table} show-wk-menu-root"

display -p '[tmux-which-key] Done'
