[pyprland]
plugins = [
    "scratchpads",
    "wallpapers",
    "expose",
    "magnify",
    "layout_center",
    "shift_monitors",
    "toggle_dpms",
    "toggle_special",
    "fetch_client_menu",
    "system_notifier",
    "shortcuts_menu"
]
notification_type = "auto"

[scratchpads.term]
command = "kitty --class=scratchpad"
class = "scratchpad"
match_by = "class"
process_tracking = false
animation = "fromTop"
size = "80% 70%"
margin = 60
position = "10% 5%"
excludes = "*"

[scratchpads.volume]
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
match_by = "class"
animation = "fromRight"
size = "35% 80%"
position = "64% 10%"
lazy = true
unfocus = "hide"
excludes = "*"

[scratchpads.files]
command = "nautilus --class=files-scratchpad"
class = "files-scratchpad"
match_by = "class"
animation = "fromLeft"
size = "65% 75%"
position = "2% 12%"
lazy = true
excludes = "*"

[scratchpads.btop]
command = "kitty --class=btop-scratchpad btop"
class = "btop-scratchpad"
match_by = "class"
animation = "fromBottom"
size = "85% 80%"
position = "7% 10%"
lazy = true
excludes = "*"

[scratchpads.music]
command = "spotify"
class = "spotify"
match_by = "class"
animation = "fromBottom"
size = "70% 75%"
position = "15% 12%"
lazy = true
excludes = "*"

[scratchpads.calc]
command = "gnome-calculator"
class = "org.gnome.Calculator"
match_by = "class"
animation = "fromTop"
size = "25% 40%"
position = "37% 5%"
lazy = true
unfocus = "hide"
excludes = "*"

[scratchpads.keepassxc]
command = "keepassxc"
class = "org.keepassxc.KeePassXC"
match_by = "class"
animation = "fromRight"
size = "50% 80%"
position = "48% 10%"
lazy = true
excludes = "*"

[scratchpads.opencode_hypr]
command = "kitty --class=opencode-hypr --directory=/home/froa/.config/hypr -e opencode --port"
class = "opencode-hypr"
match_by = "class"
process_tracking = false
animation = "fromTop"
size = "85% 85%"
position = "7% 7%"
excludes = "*"

[scratchpads.opencode_nvim]
command = "kitty --class=opencode-nvim --directory=/home/froa/.config/nvim -e opencode --port"
class = "opencode-nvim"
match_by = "class"
process_tracking = false
animation = "fromTop"
size = "85% 85%"
position = "7% 7%"
excludes = "*"

[scratchpads.opencode_cwd]
command = "kitty --class=opencode-cwd -e opencode --port"
class = "opencode-cwd"
match_by = "class"
process_tracking = false
animation = "fromTop"
size = "85% 85%"
position = "7% 7%"
excludes = "*"

[wallpapers]
path = "~/Pictures/wallpapers/"
interval = 30
extensions = ["jpg", "jpeg", "png", "webp"]
recurse = true
