#!/usr/bin/env fish
# which-key-demo.fish - Demonstration of the hierarchical menu system

# Load the plugin
source ~/.config/fish/conf.d/which_key.fish

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         FISH WHICH-KEY PLUGIN - MENU FLOW DEMONSTRATION        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "MENU HIERARCHY:"
echo ""
echo "┌─ Available Keys ─┐"
echo "│ g  Git commands"
echo "│ f  FZF commands"
echo "└──────────────────┘"
echo ""
echo "        │"
echo "        ├─ (Press 'g') ──→ ┌─ Git Commands ─┐"
echo "        │                   │ b  Branches"
echo "        │                   │ e  Each ref"
echo "        │                   │ f  Files"
echo "        │                   │ h  Hashes"
echo "        │                   │ l  Reflogs"
echo "        │                   │ r  Remotes"
echo "        │                   │ s  Stashes"
echo "        │                   │ t  Tags"
echo "        │                   │ w  Worktrees"
echo "        │                   └─────────────────┘"
echo "        │                        │"
echo "        │                        ├─ (Press 'b') ──→ Execute: git branches"
echo "        │                        ├─ (Press 'f') ──→ Execute: git files"
echo "        │                        └─ (Press 'e') ──→ Execute: git each_ref"
echo "        │"
echo "        └─ (Press 'f') ──→ ┌─ FZF Commands ──┐"
echo "                           │ c  CD directory"
echo "                           │ f  File"
echo "                           │ h  History"
echo "                           │ p  Processes"
echo "                           │ s  Git status"
echo "                           │ l  Git log"
echo "                           └─────────────────┘"
echo ""

echo "KEY BEHAVIORS:"
echo "  • Each keypress clears the previous menu"
echo "  • Invalid keys return to the previous menu level"
echo "  • ESC or 'q' exits immediately"
echo "  • Commands are executed after you leave the menu"
echo ""

echo "TRIGGER:"
echo "  Press: Ctrl+Space (in your Fish shell)"
echo ""

echo "MENU FLOW EXAMPLE:"
echo "  1. Press Ctrl+Space          → Shows 'Available Keys' menu"
echo "  2. Press 'g'                 → Clears menu, shows 'Git Commands'"
echo "  3. Press 'b'                 → Clears menu, executes: __fzf_git_sh branches"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
