# Match Ghostty/Kitty appearance
# shell=fish -c "tmux attach -t  $(tmux display-message -p '#S')"
term=xterm-256color
title=foot

font=FantasqueSansM Nerd Font Mono:size=16
letter-spacing=0
dpi-aware=no

pad=4x4

bold-text-in-bright=no

[scrollback]
lines=2000

[cursor]
style=beam
blink=no
beam-thickness=1.5

[colors]
alpha=0.65
foreground=dddddd
background=000000

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
clipboard-copy=Control+c
clipboard-paste=Control+v
search-start=Control+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G
delete-prev-word=Control+BackSpace

[text-bindings]
\x03=Control+Shift+c
