#!/usr/bin/env bash
# Autopilot: cron-scheduled AOE workers for recurring, unattended tasks.
#
# The first (and currently only) job is `daily-report`: at a scheduled time it
# spawns an AOE worker inside a dedicated git "journal" repo, seeded to run your
# productivity skills (gather-daily-info -> daily-update) and commit the Spanish
# standup to reports/<date>.md. The skills are interactive, so the worker parks
# on `input` until you attend it — the swarm dashboard flags it for you.
#
#   autopilot.sh init                       create the state dir + journal repo
#   autopilot.sh run <job>                  run a job now (this is what cron calls)
#   autopilot.sh install <job> ["<cron>"]   add a crontab entry for the job
#   autopilot.sh uninstall <job>            remove the job's crontab entry
#   autopilot.sh list                       show installed jobs + recent runs
#   autopilot.sh peek [date]                read a day's worker output (no attach)
#
# Jobs: daily-report
# Default schedule (daily-report): weekdays 16:00 Europe/Madrid  ->  "0 16 * * 1-5"
# (cron uses the system timezone, which is Europe/Madrid — DST handled by the OS)
#
# State (persists across reboots — unlike the /tmp swarm registry):
#   ~/.local/state/aoe-autopilot/
#     journal/            git repo; daily reports land in reports/<date>.md
#     registry            <date>\t<job>\t<aoe_id>\t<tmux_session>
#     log/<job>.log       run logs (cron stdout/stderr)
set -uo pipefail

# Cron runs with a minimal environment — make the tools reachable and point
# tmux at the user's default server so spawned sessions show up in your tmux.
export PATH="$HOME/.local/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export HOME="${HOME:-/home/froa}"

AOE="$(command -v aoe || echo /home/linuxbrew/.linuxbrew/bin/aoe)"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/aoe-autopilot"
JOURNAL="$STATE/journal"
REG="$STATE/registry"
LOGDIR="$STATE/log"
SELF="$(readlink -f "$0" 2>/dev/null || echo "$0")"
DEFAULT_CRON_daily_report="0 16 * * 1-5"   # weekdays 16:00 Europe/Madrid (system TZ)

log() { printf '%s [autopilot] %s\n' "$(date '+%F %T')" "$*"; }
die() { printf '❌ %s\n' "$*" >&2; exit 1; }

for bin in aoe jq tmux git; do
  command -v "$bin" >/dev/null 2>&1 || die "missing dependency: $bin"
done

aoe_sessions() { tmux list-sessions -F '#{session_name}' 2>/dev/null | grep '^aoe_' || true; }

session_state() {  # tmux_session -> working|input|done|idle
  local f="/tmp/.claude-tmux-status-${1}" raw ts
  [ -f "$f" ] || { echo idle; return; }
  raw="$(cat "$f" 2>/dev/null)"
  case "$raw" in
    input) echo input ;;
    done)  echo done ;;
    working:*) ts="${raw#working:}"; [ $(( $(date +%s) - ts )) -lt 300 ] && echo working || echo idle ;;
    *) echo idle ;;
  esac
}

init() {
  mkdir -p "$STATE" "$LOGDIR"; touch "$REG"
  if [ ! -d "$JOURNAL/.git" ]; then
    log "creating journal repo at $JOURNAL"
    mkdir -p "$JOURNAL/reports"
    git -C "$JOURNAL" init -q
    git -C "$JOURNAL" config user.name  "aoe-autopilot"
    git -C "$JOURNAL" config user.email "autopilot@localhost"
    : > "$JOURNAL/reports/.gitkeep"
    printf '# Daily report journal\n\nGenerated by autopilot. One file per day under reports/.\n' > "$JOURNAL/README.md"
    git -C "$JOURNAL" add -A
    git -C "$JOURNAL" commit -qm "init journal" || true
  fi
  log "autopilot ready. state=$STATE"
}

# Spawn an AOE worker inside $JOURNAL, seeded with $2, tracked as job $1 for today.
# Echoes nothing; appends to the registry.
spawn_worker() {
  local job="$1" seed="$2" date branch before after new id
  date="$(date +%F)"
  branch="autopilot/${job}-${date}"

  # Idempotency: if today's worker is already alive, don't spawn a second one.
  if [ -f "$REG" ] && grep -qP "^${date}\t${job}\t" "$REG"; then
    local existing_tmux
    existing_tmux="$(grep -P "^${date}\t${job}\t" "$REG" | head -1 | cut -f4)"
    if [ -n "$existing_tmux" ] && tmux has-session -t "$existing_tmux" 2>/dev/null; then
      log "$job for $date already running ($existing_tmux) — skipping"
      return 0
    fi
  fi

  before="$(aoe_sessions)"
  if ! ( cd "$JOURNAL" && "$AOE" add . -w "$branch" -b -t "${job}-${date}" -l ) >/dev/null 2>&1; then
    log "aoe add failed for $job/$date"; return 1
  fi
  id="$("$AOE" list --json 2>/dev/null | jq -r 'sort_by(.created_at)|last|.id')"
  new=""
  for _ in $(seq 1 20); do
    after="$(aoe_sessions)"
    new="$(comm -13 <(printf '%s\n' "$before" | sort -u) <(printf '%s\n' "$after" | sort -u) \
           | grep '^aoe_' | head -1)"
    [ -n "$new" ] && break
    sleep 0.5
  done
  printf '%s\t%s\t%s\t%s\n' "$date" "$job" "${id:-?}" "${new:-?}" >> "$REG"
  if [ -n "$id" ]; then
    sleep "${AUTOPILOT_SEED_DELAY:-4}"
    "$AOE" send "$id" "$seed" >/dev/null 2>&1 || true
  fi
  log "spawned $job/$date  id=${id}  tmux=${new}"
}

# ── Jobs ───────────────────────────────────────────────────────────────────
job_daily_report() {
  init
  local date seed
  date="$(date +%F)"
  # Tight, scoped seed: name the exact skills, the output path, the commit, and
  # tell the worker to ask for the interactive selections.
  seed="Run the skill gather-daily-info to build today's Daily Context Block, then run the skill daily-update to produce the Spanish standup. Save the daily-update markdown to reports/${date}.md in this repo and commit it with message 'daily report ${date}'. These skills are interactive — ask me for the in-progress ticket selections and blockers; do not invent tickets. When the report is committed, you are done."
  spawn_worker daily-report "$seed"
}

run() {
  local job="${1:?usage: autopilot.sh run <job>}"
  mkdir -p "$LOGDIR"
  case "$job" in
    daily-report) job_daily_report ;;
    *) die "unknown job: $job (known: daily-report)" ;;
  esac
}

# ── Cron management ──────────────────────────────────────────────────────────
install_job() {
  local job="${1:?usage: autopilot.sh install <job> [\"<cron>\"]}" cron="${2:-}"
  case "$job" in
    daily-report) : "${cron:=$DEFAULT_CRON_daily_report}" ;;
    *) die "unknown job: $job" ;;
  esac
  local marker="# aoe-autopilot:${job}"
  local line="${cron} ${SELF} run ${job} >> ${LOGDIR}/${job}.log 2>&1 ${marker}"
  local current; current="$(crontab -l 2>/dev/null | grep -v "$marker" || true)"
  printf '%s\n%s\n' "$current" "$line" | grep -v '^$' | crontab -
  log "installed: ${job}  schedule='${cron}'"
  log "crontab line: ${line}"
}

uninstall_job() {
  local job="${1:?usage: autopilot.sh uninstall <job>}"
  local marker="# aoe-autopilot:${job}"
  crontab -l 2>/dev/null | grep -v "$marker" | grep -v '^$' | crontab - || true
  log "uninstalled: ${job}"
}

list_jobs() {
  echo "── installed (crontab) ─────────────────────────────"
  crontab -l 2>/dev/null | grep 'aoe-autopilot' || echo "(none)"
  echo
  echo "── recent runs (registry) ──────────────────────────"
  if [ -f "$REG" ] && [ -s "$REG" ]; then
    printf '%-12s %-14s %-18s %-28s %s\n' DATE JOB ID TMUX STATE
    local date job id tmux
    tail -20 "$REG" | while IFS=$'\t' read -r date job id tmux; do
      printf '%-12s %-14s %-18s %-28s %s\n' "$date" "$job" "$id" "$tmux" "$(session_state "$tmux")"
    done
  else
    echo "(no runs yet)"
  fi
}

peek() {  # [date]  — show a day's report worker output without attaching
  local date="${1:-$(date +%F)}" id
  [ -f "$REG" ] || die "no registry yet"
  id="$(grep -P "^${date}\t" "$REG" | head -1 | cut -f3)"
  [ -z "$id" ] || [ "$id" = "?" ] && die "no worker recorded for $date"
  "$AOE" session capture "$id" -n "${2:-80}" --strip-ansi
}

case "${1:-}" in
  init)      init ;;
  run)       shift; run "$@" ;;
  install)   shift; install_job "$@" ;;
  uninstall) shift; uninstall_job "$@" ;;
  list)      list_jobs ;;
  peek)      shift; peek "$@" ;;
  *) echo "usage: autopilot.sh {init|run <job>|install <job> [\"<cron>\"]|uninstall <job>|list|peek [date]}" >&2; exit 1 ;;
esac
