# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# See https://wiki.hyprland.org/Configuring/Keywords/ for more variable settings
# These configs are mostly for laptops. This is addemdum to Keybinds.conf

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

# Lid switch - lock screen and turn off display (avoid crash by not disabling monitor)
bindl = , switch:on:Lid Switch, exec, loginctl lock-session && sleep 0.5 && hyprctl dispatch dpms off
bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on
