exec-once = hyprpm reload
exec-once = wlr-which-key
exec-once = ~/.config/hyprpanel/scripts/battery-alert.sh
exec-once = ~/.config/hyprpanel/scripts/battery-blink.sh
exec-once = pypr
exec-once = flatpak run com.slack.Slack
exec-once = ~/.config/hypr/scripts/slack-notifications.sh monitor