exec-once = sleep 2 && hyprpm reload
exec-once = wl-clip-persist --clipboard both
exec-once = wlr-which-key
exec-once = ~/.config/hyprpanel/scripts/battery-alert.sh
exec-once = ~/.config/hyprpanel/scripts/battery-blink.sh
exec-once = rm -f "$XDG_RUNTIME_DIR"/hypr/*/.pyprland.sock 2>/dev/null; sleep 1; ~/.local/bin/pypr
exec-once = ~/.config/hypr/scripts/slack-wrapper.sh
exec-once = ~/.config/hypr/scripts/slack-monitor.sh monitor
