unbind = $mainMod, SPACE
bindd = $mainMod, SPACE, open wlr-which-key, exec, /home/froa/.cargo/bin/wlr-which-key

unbind = $mainMod SHIFT, C
bindd = $mainMod SHIFT, C, reload hyprland and hyprpanel, exec, hyprctl reload; ~/.config/hypr/scripts/HyprpanelWallust.sh; pypr reload
